name: "China Telecom Monitor"
description: "中国电信话费、通话、流量套餐用量监控，提供 API 服务供 Home Assistant 调用。"
version: "1.0.0"
slug: "china_telecom_monitor"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
homeassistant_api: false
host_network: false
ports:
  8000/tcp: 8000
map:
  - addon_config:rw
options:
  telecom_user: "18912345678password"
schema:
  telecom_user: str
