name: "China Telecom Monitor"
description: "中国电信话费、通话、流量套餐用量监控，提供 API 服务供 Home Assistant 调用。"
version: "1.0.0"
slug: "china_telecom_monitor"
url: "https://github.com/hanlihanshaobo/ChinaTelecomMonitor"
init: false
arch:
  - aarch64
  - amd64
startup: application
boot: auto
homeassistant_api: false
host_network: false
image: cp0204/chinatelecommonitor:main
ports:
  10000/tcp: 10000
map:
  - config:rw
options:
  WHITELIST_NUM: "18912345678password"
schema:
  WHITELIST_NUM: str
